<a href="https://colab.research.google.com/github/thegeekybeng/iod_ai_ds_coursework_labs/blob/Module-1-Labs/submission_andrew_yeo_iod_lab_1_2_1_vector_matrix_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

In this lab you will use Python (with the NumPy library) to carry out linear algebra operations.

1. Compute the scalar product of two vectors

> In mathematics, the dot product or scalar product is an algebraic operation that takes two equal-length sequences of numbers (usually coordinate vectors) and returns a single number.

> we can calculate it this way:

        a · b = ax × bx + ay × by
        
Hint: [Dot Product](https://www.mathsisfun.com/algebra/vectors-dot-product.html)

In [ ]:
import numpy as np

In [ ]:
a = [-12, 16]
b = [12, 9]

In [ ]:
# import numpy as np

# Define vectors
a = np.array([-12, 16])
b = np.array([12, 9])

# Compute dot product
dot_product = np.dot(a, b)  # Method 1
dot_product_alt = a @ b      # Method 2 (Equivalent shorthand)

print(dot_product)  # Output: 0
print(dot_product_alt)  # Output: 0 (same result)

0
0


2. Compute the Hadamard product (entry-wise multiplication) of two vectors.

> In mathematics, the Hadamard product (also known as the Schur product[1] or the entrywise product[2]:ch. 5) is a binary operation that takes two matrices of the same dimensions and produces another matrix of the same dimension as the operands where each element i, j is the product of elements i, j of the original two matrices. It should not be confused with the more common matrix product. It is attributed to, and named after, either French mathematician Jacques Hadamard or German mathematician Issai Schur. [Wiki](https://en.wikipedia.org/wiki/Hadamard_product_(matrices))

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/4eb9bb54b2820fb3583901ec05bc4b474b6d90bc)

In [ ]:
a = np.matrix([[1,2],[3,4]])
b = np.matrix([[5,6],[7,8]])

In [ ]:
np.multiply(a,b)

matrix([[ 5, 12],
        [21, 32]])

In [ ]:
#desired output:
# np.array([[5,12],[21,32]])

3. Compute the sum of two matrices.

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/0fb7845af355c550d44020e52699069c044126a9)

In [ ]:
# Add two matrices using a nested loop

X = [[1,2,3],
    [4,5,6],
    [7,8,9]]

Y = [[2,3,7],
    [1,4,9],
    [3,2,3]]

In [ ]:
# import numpy as np

# Define the two matrices
A = np.matrix([
    [1, 2, 5],
    [2, 4, 7],
    [6, 5, 6]
])

B = np.matrix([
    [2, 3, 5],
    [3, 5, 8],
    [4, 5, 6]
])

# Compute the sum of the matrices
matrix_sum = A + B  # Method 1
matrix_sum_alt = np.add(A, B)  # Method 2

# Print the result
print(matrix_sum)


[[ 3  5 10]
 [ 5  9 15]
 [10 10 12]]


In [ ]:
#desired output:
#[[3,5,10],
# [5,9,15],
# [10,10,12]]

4. Compute the product of two matrices.

![](https://upload.wikimedia.org/wikipedia/commons/e/eb/Matrix_multiplication_diagram_2.svg)

In [ ]:
# Program to multiply two matrices using nested loops

# 3x3 matrix
X = [[7, 2, 4],
    [3, 9, 5],
    [8, 1, 6]]

# 3x4 matrix
Y = [[5,8,2,6],
    [1,4,9,3],
    [7,2,5,8]]

#X is 3 x 3, #Y is 3 x 4 matrix
#result of XY is 3 x 4 matrix.

In [ ]:
np.matmul(X,Y)

array([[ 65,  72,  52,  80],
       [ 59,  70, 112,  85],
       [ 83,  80,  55,  99]])

In [ ]:
#desired output:
#[[65, 72, 52, 80],
# [59, 70, 112, 85],
# [83, 80, 55, 99]]

5. Compute the determinant of an n x n matrix.

Hint: Use
> np.linalg.det

In [ ]:
matrix = [[-2,2,-3],[-1,1,3],[2,0,-1]]

In [ ]:
from numpy.linalg import inv
from numpy.linalg import det

det(matrix)

17.999999999999996

6. Compute the inverse of an n x n matrix.

Hint: Use
> `

In [ ]:
a = np.array([[1., 2.], [3., 4.]])

In [ ]:
import numpy as np

# Define the matrix
A = np.array([[1., 2.], [3., 4.]])

# Compute inverse
A_inv = np.linalg.inv(A)

# Print result
print(A_inv)


[[-2.   1. ]
 [ 1.5 -0.5]]


7. (Application)
Three customers made the following purchases of three different items at an office supply store:
* Customer W bought 2 notebooks, 4 pens and 3 staplers for \$38.80
* Customer X bought 3 notebooks, 3 pens and 2 staplers for \$32.00
* Customer Y bought 4 notebooks, 8 pens and 1 stapler for \$36.60

Based on this, how much did customer Z spend in buying 1 notebook, 2 pens and 4 staplers?

In [ ]:
A = np.matrix([[2,4,3], [3,3,2], [4,8,1]])
b = np.array([38.80, 32.00, 36.60])
print(A)

v = inv(A)
result = np.matmul(v,b.T)
print(result)

[[2 4 3]
 [3 3 2]
 [4 8 1]]
[[3.3 1.9 8.2]]


In [ ]:
# Define the cost of items from solution x
notebook_price = x.item(0)  # Cost of one notebook
pen_price = x.item(1)       # Cost of one pen
stapler_price = x.item(2)   # Cost of one stapler

# Compute Customer Z's total expenditure
customer_z_cost = (1 * notebook_price) + (2 * pen_price) + (4 * stapler_price)

# Print results with formatted output
print(f"The cost of each stationery is {notebook_price:.2f} for notebooks, {pen_price:.2f} for pens, and {stapler_price:.2f} for staplers.")
print(f"Customer Z expenditure for 1 notebook, 2 pens, and 4 staplers adds up to ${customer_z_cost:.2f}")

The cost of each stationery is 3.30 for notebooks, 1.90 for pens, and 8.20 for staplers.
Customer Z expenditure for 1 notebook, 2 pens, and 4 staplers adds up to $39.90




---



---



> > > > > > > > > © 2025 Institute of Data


---



---



